[package]
name = "ma_ffi"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro=true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2.workspace =true
quote.workspace = true

